### PR TITLE
safer handling of super properties

### PR DESCRIPTION
**Pull request by zihejia**
address https://github.com/mixpanel/mixpanel-react-native/issues/179

### CODE REVIEW

**Review by jaredmixpanel — APPROVED** [review]

**Comment by matthewmturner** [comment]
@zihejia @jaredmixpanel thanks for this. any idea when the fix will be released?

**Comment by matthewmturner** [comment]
@zihejia @jaredmixpanel anything on this? we were actually in the middle of removing mixpanel from our app because of this issue.  but im ok to put that work on pause and see if the fix you have here works.  any information you could share on this would be greatly appreciated.

**Comment by zihejia** [comment]
hi @matthewmturner , I will release it by tomorrow.

**Comment by matthewmturner** [comment]
@zihejia Thank you. For my information can you provide color on what the issue was?

**Comment by zihejia** [comment]
hi @matthewmturner , this might relate to the race conditions that mutate the properties during the initialization.

**Pull request merged**
